# NumPy & Pandas Assignment

## Link: Retail_Dataset

## Import Library and Load Dataset

**Answer:**

Below code loads `Retail_Dataset.csv`.  
If the file is not available, it creates a small sample dataset so the notebook can still run.

In [27]:
import pandas as pd
import numpy as np


df = pd.read_csv("C:\\Users\\Chittaranjan\\Downloads\\retail_dataset .csv")
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

## Question 1

**Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.**

**Answer:**

In [21]:
# First 5 rows
df.head()

         Date Product Category Region  Quantity  Price
0  2023-01-05      Electronics   East       5.0  200.0
1  2023-01-12         Clothing   West      10.0   50.0
2  2023-02-03          Grocery  North       NaN   20.0
3  2023-02-18      Electronics  South       7.0    NaN
4  2023-03-07              NaN   East       6.0  150.0

## Question 1 - Dataset Information

**Dataset information**

**Answer:**

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

## Question 2

**Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.**

**Answer:**

In [29]:
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values)

print("\nTotal missing values in the dataset:")
print(missing_values.sum())

Missing values in each column:
Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

Total missing values in the dataset:
12

## Question 3

**Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.**

**Answer:**

In [30]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())

df[["Quantity", "Price"]]

    Quantity   Price
0        7.0   167.0
1        4.0   374.0
2        8.0  1059.0
3        5.0   304.0
4        7.0   282.0
..       ...     ...
95      10.0  2901.0
96       9.0  1077.0
97       7.0   643.0
98       9.0   429.0
99       8.0  1183.0

[100 rows x 2 columns]

In [31]:
missing_values = df.isnull().sum()
missing_values

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            0
Price               0
Date                0
Region              2
dtype: int64

## Question 4

**Q4. Remove all rows where the Product Category or Region column contains missing values.**

**Answer:**

In [32]:
df = df.dropna(subset=["Product Category", "Region"])
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

## Question 5

**Q5. Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.**

**Answer:**

In [40]:
df["Revenue"] = np.multiply(df["Quantity"], df["Price"])
df

C:\Users\Chittaranjan\AppData\Local\Temp\ipykernel_13540\1264273871.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Revenue"] = np.multiply(df["Quantity"], df["Price"])

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue,Month
0,T001,C015,Books,7.0,167.0,2023-02-02,North,1169.0,2
1,T002,C004,Toys,4.0,374.0,2023-02-17,South,1496.0,2
2,T003,C033,Furniture,8.0,1059.0,2024-05-17,South,8472.0,5
3,T004,C047,Groceries,5.0,304.0,2024-02-11,South,1520.0,2
4,T005,C022,Books,7.0,282.0,2024-07-27,West,1974.0,7
...,...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,2023-08-08,North,29010.0,8
96,T097,C021,Clothing,9.0,1077.0,2024-07-19,North,9693.0,7
97,T098,C015,Clothing,7.0,643.0,2023-08-13,North,4501.0,8
98,T099,C005,Groceries,9.0,429.0,2024-01-20,South,3861.0,1
99,T100,C010,Furniture,8.0,1183.0,2024-02-07,North,9464.0,2

## Question 6

**Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.**

**Answer:**

In [8]:
total_revenue = np.sum(df["Revenue"])
print("Total Revenue:", total_revenue)

Total Revenue: 6642.5

## Question 7

**Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.**

**Answer:**

In [34]:
category_revenue = df.groupby("Product Category")["Revenue"].sum()
category_revenue

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

## Question 8

**Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.**

**Answer:**

In [35]:
top_3_categories = category_revenue.sort_values(ascending=False).head(3)
bottom_3_categories = category_revenue.sort_values(ascending=True).head(3)

print("Top 3 Categories with Highest Revenue:")
print(top_3_categories)

print("\nBottom 3 Categories with Lowest Revenue:")
print(bottom_3_categories)

Top 3 Categories with Highest Revenue:
Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64

Bottom 3 Categories with Lowest Revenue:
Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

## Question 9

**Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue.**

**Answer:**

In [36]:
region_revenue = df.groupby("Region")["Revenue"].sum()

print("Revenue by Region:")
print(region_revenue)

print("\nRegion with Highest Revenue:")
print(region_revenue.idxmax(), "-", region_revenue.max())

print("\nRegion with Lowest Revenue:")
print(region_revenue.idxmin(), "-", region_revenue.min())

Revenue by Region:
Region
East     126232.044039
North    153244.353383
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64

Region with Highest Revenue:
North - 153244.35338345866

Region with Lowest Revenue:
West - 81197.52631578947

## Question 10

**Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy.**

**Answer:**

In [39]:
import pandas as pd
import numpy as np

# Fix date format
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# Extract month
df["Month"] = df["Date"].dt.month

# Monthly revenue
monthly_revenue = df.groupby("Month")["Revenue"].sum()

print("Monthly Revenue:")
print(monthly_revenue)

# Statistics using NumPy
print("\nMean Revenue:", np.mean(df["Revenue"]))
print("Median Revenue:", np.median(df["Revenue"]))
print("Standard Deviation of Revenue:", np.std(df["Revenue"]))

Monthly Revenue:
Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64

Mean Revenue: 4900.312216631804
Median Revenue: 3282.1052631578946
Standard Deviation of Revenue: 4721.171795257337

C:\Users\Chittaranjan\AppData\Local\Temp\ipykernel_13540\583682312.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
C:\Users\Chittaranjan\AppData\Local\Temp\ipykernel_13540\583682312.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"] = df["Date"].dt.month